//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookKeeperNewJosh.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BookListings = new HashSet<BookListing>();
            this.Departments = new HashSet<Department>();
        }
        [Key]
        public int studentNo { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string password { get; set; }
        public bool isBlacklisted { get; set; }
        public string email { get; set; }
        public int totalrating { get; set; }
        public int ratingcount { get; set; }
        public string blacklistReason { get; set; }
        public Nullable<bool> appealed { get; set; }
        public string appealReason { get; set; }
        public Nullable<bool> reported { get; set; }
        public string reportReason { get; set; }

        public float realRating { get { if (ratingcount == 0) return 5; else return totalrating / ratingcount; } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookListing> BookListings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Departments { get; set; }
    }
}
